spring:
  application:
    name: music-api
  profiles:
    active: oracle
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

api:
  security:
    token:
      secret: oi

secret: oi

spotify:
  client-id: ${SPOTIFY_CLIENT_ID:f90815d9e9e64c16accca3e6dcddf217}
  client-secret: ${SPOTIFY_CLIENT_SECRET:1fefb820481d44719190bb471464cbab}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      m8music-api:
        minimumNumberOfCalls: 4
        slidingWindowSize: 8
  retry:
    instances:
      m8music-api:
        exponential-backoff-multiplier: 2
        enable-exponential-backoff: false
        wait-duration: 5s
        max-attempts: 2
      spotify:
        max-attempts: 3
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        wait-duration: 5s
        retry-exceptions:
          - feign.FeignException$BadGateway
          - feign.FeignException$ServiceUnavailable
          - feign.FeignException$InternalServerError
